[package]
name = "tjs2dec"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "A krkr2 and krkrz tjs2 bytecode decompiler written in Rust"
repository = "https://github.com/xmoezzz/tjs2Decompiler"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
